name: test
on:
  push:
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "8.0.x"
  SLN_PATH: "UnityReleaseNoteMCP.slnx"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test "${SLN_PATH}" --no-restore --verbosity normal